app_dir: /opt/apps/charm

api_image: ghcr.io/andrewb-codes/charm-back-fastapi-api
frontend_image: ghcr.io/andrewb-codes/charm-back-fastapi-frontend
app_image_tag: main

api_image_ref: "{{ api_image }}:{{ app_image_tag }}"
frontend_image_ref: "{{ frontend_image }}:{{ app_image_tag }}"

docker_public_network: web
frontend_network_alias: charm-frontend

app_env:
  DATABASE_URL: postgresql+asyncpg://charm_user:{{ postgres_password }}@postgres:5432/charm
  JWT_SECRET: "{{ jwt_secret }}"
  STREAMLIT_API_URL: http://api:8000
  POSTGRES_DB: charm
  POSTGRES_USER: charm_user
  POSTGRES_PASSWORD: "{{ postgres_password }}"
