app_dir: /opt/apps/charm
app_image: ghcr.io/andrewb-codes/charm-back-fastapi
app_image_tag: main
app_image_ref: "{{ app_image }}:{{ app_image_tag }}"

docker_public_network: web
frontend_network_alias: charm-frontend

app_env:
  DATABASE_URL: postgresql+asyncpg://charm_user:{{ postgres_password }}@postgres:5432/charm
  JWT_SECRET: "{{ jwt_secret }}"
  STREAMLIT_API_URL: http://api:8000
  POSTGRES_DB: charm
  POSTGRES_USER: charm_user
  POSTGRES_PASSWORD: "{{ postgres_password }}"
