"""create profile like table

Revision ID: 698fdfdd5bb7
Revises: 9bef997f9dfc
Create Date: 2026-06-20 23:44:01.728243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "698fdfdd5bb7"
down_revision: Union[str, Sequence[str], None] = "9bef997f9dfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_like",
        sa.Column("a_profile", sa.BigInteger(), nullable=False),
        sa.Column("b_profile", sa.BigInteger(), nullable=False),
        sa.Column("liked_a", sa.Boolean(), nullable=True),
        sa.Column("liked_b", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("a_profile < b_profile", name="profile_like_order_check"),
        sa.ForeignKeyConstraint(["a_profile"], ["profile.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["b_profile"], ["profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("a_profile", "b_profile"),
    )
    op.create_index(
        "ix_profile_like_a_profile", "profile_like", ["a_profile"], unique=False
    )
    op.create_index(
        "ix_profile_like_b_profile", "profile_like", ["b_profile"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_profile_like_b_profile", table_name="profile_like")
    op.drop_index("ix_profile_like_a_profile", table_name="profile_like")
    op.drop_table("profile_like")
    # ### end Alembic commands ###
